### ISSUE TITLE
 Compilation errors when building dhcpcd on a mipsel target using musl

### ISSUE THREAD

**Issue by gtxaspec** [NetworkConfiguration/dhcpcd#373]
We encountered several compilation errors while attempting to build the latest dhcpcd master branch on a mipsel target with musl. These errors seem to be related to redefinitions of certain network structures (struct ifmap, struct ifreq, struct ifconf) when both linux/if.h and net/if.h are included.

```
for x in src hooks; do cd $x; make all || exit $?; cd ..; done
make[1]: Entering directory '/tmp/dhcpcd/src'
mipsel-linux-gcc -O2 -g -Wall -Wextra -Wundef -Wmissing-prototypes -Wmissing-declarations -Wmissing-format-attribute -Wnested-externs -Winline -Wcast-align -Wcast-qual -Wpointer-arith -Wreturn-type -Wswitch -Wshadow -Wcast-qual -Wwrite-strings -Wformat=2 -Wpointer-sign -Wmissing-noreturn -Wredundant-decls -Wconversion -Wstrict-overflow -Wlogical-op -std=c99 -DHAVE_CONFIG_H -D_GNU_SOURCE -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -D_LARGEFILE64_SOURCE -DINET -DARP -DARPING -DIPV4LL -DINET6 -DDHCP6 -DAUTH -DPRIVSEP -I.. -I../src -I./crypt -c if-linux.c -o if-linux.o
In file included from /home/aag/toolchain/mipsel-thingino-linux-musl_sdk-buildroot/mipsel-thingino-linux-musl/sysroot/usr/include/linux/netdevice.h:28,
                 from /home/aag/toolchain/mipsel-thingino-linux-musl_sdk-buildroot/mipsel-thingino-linux-musl/sysroot/usr/include/linux/if_arp.h:26,
                 from if-linux.c:60:
/home/aag/toolchain/mipsel-thingino-linux-musl_sdk-buildroot/mipsel-thingino-linux-musl/sysroot/usr/include/linux/if.h:142:8: error: redefinition of ‘struct ifmap’
  142 | struct ifmap {
      |        ^~~~~
In file included from if-linux.c:49:
/home/aag/toolchain/mipsel-thingino-linux-musl_sdk-buildroot/mipsel-thingino-linux-musl/sysroot/usr/include/net/if.h:64:8: note: originally defined here
   64 | struct ifmap {
      |        ^~~~~
/home/aag/toolchain/mipsel-thingino-linux-musl_sdk-buildroot/mipsel-thingino-linux-musl/sysroot/usr/include/linux/if.h:176:8: error: redefinition of ‘struct ifreq’
  176 | struct ifreq {
      |        ^~~~~
/home/aag/toolchain/mipsel-thingino-linux-musl_sdk-buildroot/mipsel-thingino-linux-musl/sysroot/usr/include/net/if.h:76:8: note: originally defined here
   76 | struct ifreq {
      |        ^~~~~
/home/aag/toolchain/mipsel-thingino-linux-musl_sdk-buildroot/mipsel-thingino-linux-musl/sysroot/usr/include/linux/if.h:225:8: error: redefinition of ‘struct ifconf’
  225 | struct ifconf  {
      |        ^~~~~~
/home/aag/toolchain/mipsel-thingino-linux-musl_sdk-buildroot/mipsel-thingino-linux-musl/sysroot/usr/include/net/if.h:116:8: note: originally defined here
  116 | struct ifconf {
      |        ^~~~~~
if-linux.c: In function ‘if_copyrt’:
if-linux.c:136:44: warning: conversion to ‘size_t’ {aka ‘unsigned int’} from ‘int’ may change the sign of the result [-Wsign-conversion]
  136 | #define RTA_NEXT(rta, attrlen)  ((attrlen) -= RTA_ALIGN((rta)->rta_len), \
      |                                            ^~
if-linux.c:681:40: note: in expansion of macro ‘RTA_NEXT’
  681 |         for (; RTA_OK(rta, len); rta = RTA_NEXT(rta, len)) {
      |                                        ^~~~~~~~
if-linux.c:694:52: warning: unsigned conversion from ‘int’ to ‘unsigned int’ changes value from ‘-4’ to ‘4294967292’ [-Wsign-conversion]
  694 |                         ifindex = *(unsigned int *)RTA_DATA(rta);
      |                                                    ^~~~~~~~
if-linux.c:698:58: warning: unsigned conversion from ‘int’ to ‘unsigned int’ changes value from ‘-4’ to ‘4294967292’ [-Wsign-conversion]
  698 |                         rt->rt_metric = *(unsigned int *)RTA_DATA(rta);
      |                                                          ^~~~~~~~
if-linux.c:706:47: warning: unsigned conversion from ‘int’ to ‘unsigned int’ changes value from ‘-4’ to ‘4294967292’ [-Wsign-conversion]
  706 |                         r2 = (struct rtattr *)RTA_DATA(rta);
      |                                               ^~~~~~~~
if-linux.c:136:44: warning: conversion to ‘size_t’ {aka ‘unsigned int’} from ‘int’ may change the sign of the result [-Wsign-conversion]
  136 | #define RTA_NEXT(rta, attrlen)  ((attrlen) -= RTA_ALIGN((rta)->rta_len), \
      |                                            ^~
if-linux.c:707:53: note: in expansion of macro ‘RTA_NEXT’
  707 |                         for (; RTA_OK(r2, l2); r2 = RTA_NEXT(r2, l2)) {
      |                                                     ^~~~~~~~
if-linux.c:710:71: warning: unsigned conversion from ‘int’ to ‘unsigned int’ changes value from ‘-4’ to ‘4294967292’ [-Wsign-conversion]
  710 |                                         rt->rt_mtu = *(unsigned int *)RTA_DATA(r2);
      |                                                                       ^~~~~~~~
if-linux.c:725:64: warning: unsigned conversion from ‘int’ to ‘unsigned int’ changes value from ‘-4’ to ‘4294967292’ [-Wsign-conversion]
  725 |                         memcpy((char *)sa + sa_addroffset(sa), RTA_DATA(rta),
      |                                                                ^~~~~~~~
if-linux.c:726:29: warning: unsigned conversion from ‘int’ to ‘unsigned int’ changes value from ‘-4’ to ‘4294967292’ [-Wsign-conversion]
  726 |                             MIN(salen, RTA_PAYLOAD(rta)));
      |                             ^~~
if-linux.c:726:29: warning: unsigned conversion from ‘int’ to ‘unsigned int’ changes value from ‘-4’ to ‘4294967292’ [-Wsign-conversion]
if-linux.c: In function ‘link_addr’:
if-linux.c:136:44: warning: conversion to ‘size_t’ {aka ‘unsigned int’} from ‘int’ may change the sign of the result [-Wsign-conversion]
  136 | #define RTA_NEXT(rta, attrlen)  ((attrlen) -= RTA_ALIGN((rta)->rta_len), \
      |                                            ^~
if-linux.c:851:48: note: in expansion of macro ‘RTA_NEXT’
  851 |                 for (; RTA_OK(rta, len); rta = RTA_NEXT(rta, len)) {
      |                                                ^~~~~~~~
if-linux.c:855:61: warning: unsigned conversion from ‘int’ to ‘unsigned int’ changes value from ‘-4’ to ‘4294967292’ [-Wsign-conversion]
  855 |                                         memcpy(&brd.s_addr, RTA_DATA(rta),
      |                                                             ^~~~~~~~
if-linux.c:860:53: warning: unsigned conversion from ‘int’ to ‘unsigned int’ changes value from ‘-4’ to ‘4294967292’ [-Wsign-conversion]
  860 |                                 memcpy(&brd.s_addr, RTA_DATA(rta),
      |                                                     ^~~~~~~~
if-linux.c:864:54: warning: unsigned conversion from ‘int’ to ‘unsigned int’ changes value from ‘-4’ to ‘4294967292’ [-Wsign-conversion]
  864 |                                 memcpy(&addr.s_addr, RTA_DATA(rta),
      |                                                      ^~~~~~~~
if-linux.c:136:44: warning: conversion to ‘size_t’ {aka ‘unsigned int’} from ‘int’ may change the sign of the result [-Wsign-conversion]
  136 | #define RTA_NEXT(rta, attrlen)  ((attrlen) -= RTA_ALIGN((rta)->rta_len), \
      |                                            ^~
if-linux.c:890:48: note: in expansion of macro ‘RTA_NEXT’
  890 |                 for (; RTA_OK(rta, len); rta = RTA_NEXT(rta, len)) {
      |                                                ^~~~~~~~
if-linux.c:893:63: warning: unsigned conversion from ‘int’ to ‘unsigned int’ changes value from ‘-4’ to ‘4294967292’ [-Wsign-conversion]
  893 |                                 address6 = (struct in6_addr *)RTA_DATA(rta);
      |                                                               ^~~~~~~~
if-linux.c:896:61: warning: unsigned conversion from ‘int’ to ‘unsigned int’ changes value from ‘-4’ to ‘4294967292’ [-Wsign-conversion]
  896 |                                 local6 = (struct in6_addr *)RTA_DATA(rta);
      |                                                             ^~~~~~~~
if-linux.c: In function ‘link_neigh’:
if-linux.c:136:44: warning: conversion to ‘size_t’ {aka ‘unsigned int’} from ‘int’ may change the sign of the result [-Wsign-conversion]
  136 | #define RTA_NEXT(rta, attrlen)  ((attrlen) -= RTA_ALIGN((rta)->rta_len), \
      |                                            ^~
if-linux.c:968:48: note: in expansion of macro ‘RTA_NEXT’
  968 |                 for (; RTA_OK(rta, len); rta = RTA_NEXT(rta, len)) {
      |                                                ^~~~~~~~
if-linux.c:971:56: warning: unsigned conversion from ‘int’ to ‘unsigned int’ changes value from ‘-4’ to ‘4294967292’ [-Wsign-conversion]
  971 |                                 memcpy(&addr6.s6_addr, RTA_DATA(rta),
      |                                                        ^~~~~~~~
if-linux.c: In function ‘link_netlink’:
if-linux.c:136:44: warning: conversion to ‘size_t’ {aka ‘unsigned int’} from ‘int’ may change the sign of the result [-Wsign-conversion]
  136 | #define RTA_NEXT(rta, attrlen)  ((attrlen) -= RTA_ALIGN((rta)->rta_len), \
      |                                            ^~
if-linux.c:1020:40: note: in expansion of macro ‘RTA_NEXT’
 1020 |         for (; RTA_OK(rta, len); rta = RTA_NEXT(rta, len)) {
      |                                        ^~~~~~~~
if-linux.c:1029:46: warning: unsigned conversion from ‘int’ to ‘unsigned int’ changes value from ‘-4’ to ‘4294967292’ [-Wsign-conversion]
 1029 |                         strlcpy(ifn, (char *)RTA_DATA(rta), sizeof(ifn));
      |                                              ^~~~~~~~
if-linux.c:1077:46: warning: unsigned conversion from ‘int’ to ‘unsigned int’ changes value from ‘-4’ to ‘4294967292’ [-Wsign-conversion]
 1077 |                 void *hwa = hwaddr != NULL ? RTA_DATA(hwaddr) : NULL;
      |                                              ^~~~~~~~
if-linux.c:1080:58: warning: unsigned conversion from ‘int’ to ‘unsigned int’ changes value from ‘-4’ to ‘4294967292’ [-Wsign-conversion]
 1080 |                 if (hwaddr != NULL && hwaddr->rta_len != RTA_LENGTH(hwl))
      |                                                          ^~~~~~~~~~
if-linux.c: In function ‘add_attr_l’:
if-linux.c:1191:46: warning: unsigned conversion from ‘int’ to ‘unsigned int’ changes value from ‘-4’ to ‘4294967292’ [-Wsign-conversion]
 1191 |         unsigned short len = (unsigned short)RTA_LENGTH(alen);
      |                                              ^~~~~~~~~~
if-linux.c:1194:39: warning: conversion to ‘__u32’ {aka ‘unsigned int’} from ‘int’ may change the sign of the result [-Wsign-conversion]
 1194 |         if (NLMSG_ALIGN(n->nlmsg_len) + RTA_ALIGN(len) > maxlen) {
      |                                       ^
if-linux.c:1203:24: warning: unsigned conversion from ‘int’ to ‘unsigned int’ changes value from ‘-4’ to ‘4294967292’ [-Wsign-conversion]
 1203 |                 memcpy(RTA_DATA(rta), data, alen);
      |                        ^~~~~~~~
if-linux.c:1204:50: warning: conversion to ‘__u32’ {aka ‘unsigned int’} from ‘int’ may change the sign of the result [-Wsign-conversion]
 1204 |         n->nlmsg_len = NLMSG_ALIGN(n->nlmsg_len) + RTA_ALIGN(len);
      |                                                  ^
if-linux.c: In function ‘add_attr_32’:
if-linux.c:1221:30: warning: unsigned conversion from ‘int’ to ‘unsigned int’ changes value from ‘-4’ to ‘4294967292’ [-Wsign-conversion]
 1221 |         unsigned short len = RTA_LENGTH(sizeof(data));
      |                              ^~~~~~~~~~
if-linux.c:1232:16: warning: unsigned conversion from ‘int’ to ‘unsigned int’ changes value from ‘-4’ to ‘4294967292’ [-Wsign-conversion]
 1232 |         memcpy(RTA_DATA(rta), &data, sizeof(data));
      |                ^~~~~~~~
if-linux.c: In function ‘rta_add_attr_32’:
if-linux.c:1242:30: warning: unsigned conversion from ‘int’ to ‘unsigned int’ changes value from ‘-4’ to ‘4294967292’ [-Wsign-conversion]
 1242 |         unsigned short len = RTA_LENGTH(sizeof(data));
      |                              ^~~~~~~~~~
if-linux.c:1253:16: warning: unsigned conversion from ‘int’ to ‘unsigned int’ changes value from ‘-4’ to ‘4294967292’ [-Wsign-conversion]
 1253 |         memcpy(RTA_DATA(subrta), &data, sizeof(data));
      |                ^~~~~~~~
if-linux.c: In function ‘_if_addressexists’:
if-linux.c:136:44: warning: conversion to ‘size_t’ {aka ‘unsigned int’} from ‘int’ may change the sign of the result [-Wsign-conversion]
  136 | #define RTA_NEXT(rta, attrlen)  ((attrlen) -= RTA_ALIGN((rta)->rta_len), \
      |                                            ^~
if-linux.c:1535:40: note: in expansion of macro ‘RTA_NEXT’
 1535 |         for (; RTA_OK(rta, len); rta = RTA_NEXT(rta, len)) {
      |                                        ^~~~~~~~
if-linux.c:1538:44: warning: unsigned conversion from ‘int’ to ‘unsigned int’ changes value from ‘-4’ to ‘4294967292’ [-Wsign-conversion]
 1538 |                         memcpy(&this_addr, RTA_DATA(rta), sizeof(this_addr));
      |                                            ^~~~~~~~
if-linux.c: In function ‘if_route’:
if-linux.c:1663:44: warning: unsigned conversion from ‘int’ to ‘unsigned int’ changes value from ‘-4’ to ‘4294967292’ [-Wsign-conversion]
 1663 |                         metrics->rta_len = RTA_LENGTH(0);
      |                                            ^~~~~~~~~~
if-linux.c:1667:29: warning: unsigned conversion from ‘int’ to ‘unsigned int’ changes value from ‘-4’ to ‘4294967292’ [-Wsign-conversion]
 1667 |                             RTA_DATA(metrics),
      |                             ^~~~~~~~
if-linux.c:1668:45: warning: unsigned conversion from ‘int’ to ‘unsigned int’ changes value from ‘-4’ to ‘4294967292’ [-Wsign-conversion]
 1668 |                             (unsigned short)RTA_PAYLOAD(metrics));
      |                                             ^~~~~~~~~~~
if-linux.c: In function ‘bpf_read’:
if-linux.c:1858:29: warning: unsigned conversion from ‘long int’ to ‘long unsigned int’ changes value from ‘-4’ to ‘4294967292’ [-Wsign-conversion]
 1858 |                      cmsg = CMSG_NXTHDR(&msg, cmsg))
      |                             ^~~~~~~~~~~
if-linux.c:1858:29: warning: unsigned conversion from ‘long int’ to ‘long unsigned int’ changes value from ‘-4’ to ‘4294967292’ [-Wsign-conversion]
if-linux.c: In function ‘if_address6’:
if-linux.c:1998:7: warning: "IFA_F_MANAGETEMPADDR" is not defined, evaluates to 0 [-Wundef]
 1998 | #elif IFA_F_MANAGETEMPADDR
      |       ^~~~~~~~~~~~~~~~~~~~
if-linux.c: In function ‘_if_addrflags6’:
if-linux.c:136:44: warning: conversion to ‘size_t’ {aka ‘unsigned int’} from ‘int’ may change the sign of the result [-Wsign-conversion]
  136 | #define RTA_NEXT(rta, attrlen)  ((attrlen) -= RTA_ALIGN((rta)->rta_len), \
      |                                            ^~
if-linux.c:2046:40: note: in expansion of macro ‘RTA_NEXT’
 2046 |         for (; RTA_OK(rta, len); rta = RTA_NEXT(rta, len)) {
      |                                        ^~~~~~~~
if-linux.c:2049:54: warning: unsigned conversion from ‘int’ to ‘unsigned int’ changes value from ‘-4’ to ‘4294967292’ [-Wsign-conversion]
 2049 |                         address = (struct in6_addr *)RTA_DATA(rta);
      |                                                      ^~~~~~~~
if-linux.c:2052:52: warning: unsigned conversion from ‘int’ to ‘unsigned int’ changes value from ‘-4’ to ‘4294967292’ [-Wsign-conversion]
 2052 |                         local = (struct in6_addr *)RTA_DATA(rta);
      |                                                    ^~~~~~~~
if-linux.c:2054:22: error: ‘IFA_FLAGS’ undeclared (first use in this function)
 2054 |                 case IFA_FLAGS:
      |                      ^~~~~~~~~
if-linux.c:2054:22: note: each undeclared identifier is reported only once for each function it appears in
if-linux.c:2055:45: warning: unsigned conversion from ‘int’ to ‘unsigned int’ changes value from ‘-4’ to ‘4294967292’ [-Wsign-conversion]
 2055 |                         flags = (uint32_t *)RTA_DATA(rta);
      |                                             ^~~~~~~~
if-linux.c: At top level:
if-linux.c:1210:1: warning: ‘add_attr_8’ defined but not used [-Wunused-function]
 1210 | add_attr_8(struct nlmsghdr *n, unsigned short maxlen, unsigned short type,
      | ^~~~~~~~~~
make[1]: *** [Makefile:55: if-linux.o] Error 1
make[1]: Leaving directory '/tmp/dhcpcd/src'
make: *** [Makefile:25: all] Error 2
```

**Comment by rsmarples** [comment]
I am able to build fine on Alpine linux using musl on x86_64.
It looks like you really need this patch from musl: https://git.musl-libc.org/cgit/musl/commit/include/net/if.h?id=b583c5d3b4cc2c54c68eef5eb7855ecfacee8bfc

Anyway, I've pushed a fix which might also fix it for you if your musl defines IFF_DORMANT.

**Comment by gtxaspec** [comment]
@rsmarples Thanks for providing the fix! Unfortunately, it doesn't seem to have resolved the issue. I also verified that we already have the patch from musl applied. 

The errors remain unchanged from before.

**Comment by rsmarples** [comment]
So what is including linux/if.h then?
Because your musl is not defining IFF_DORMANT then it is likely not defining the other stuff to avoid re-definitions either.

But what's more worrying is this error which I just spotted:
> if-linux.c:2054:22: error: ‘IFA_FLAGS’ undeclared (first use in this function)

What version of kernel headers are you building against?

**Comment by gtxaspec** [comment]
We're using kernel headers version 3.10.14 on a MIPSLE platform, with a toolchain built via Buildroot musl and GCC 14. 

Heres the full build log for brevity: https://gist.github.com/gtxaspec/d0260bc0cf60db725ce7f12274778421

**Comment by rsmarples** [comment]
So you need to pass `CC=mipsel-linux-gcc` to configure as well as configure found functions like `arc4random` and `closefrom` which aren't present on the toolchain you're building for. Please do this and repost full logs as that will cleanup some noise hopefully.
