### ISSUE TITLE
10.4.2 now reports 'malformed embedded option'  from router

### ISSUE THREAD

**Issue by TheEpeeist** [NetworkConfiguration/dhcpcd#508]
Following the upgrade from 10.2.3  to 10.2.4 dhcpcd began to log 
`Jun 06 22:16:43 dhcpcd[671]: eno2: dhcp_envoption 24.0/3: malformed embedded option`
at irregular intervals of between 20 and 50 seconds.

The output of dhcpcd -T shows:

```
dhcpcd-10.2.4 starting
dev: loaded udev
dhcp6_openudp: Address already in use
ps_inet_startcb: dhcp6_open: Address already in use
DUID 00:01:00:01:2d:81:ea:89:2c:fd:a1:bb:a1:64
wlo1: waiting for carrier
eno2: IAID a1:bb:a1:64
eno2: soliciting an IPv6 router
eno2: Router Advertisement from fe80::8e83:94ff:fe7f:c989
interface=eno2
pid=101050
protocol=ra
reason=TEST
ifcarrier=up
ifflags=69699
ifmetric=1003
ifmtu=1500
ifwireless=0
nd1_acquired=47696
nd1_addr1=2a00:23c7:5a1f:d901:d99e:cc3f:57b9:7301/64
nd1_flags=O
nd1_from=fe80::8e83:94ff:fe7f:c989
nd1_hoplimit=64
nd1_lifetime=180
nd1_mtu=1492
nd1_now=47696
nd1_prefix_information1_flags=LAH
nd1_prefix_information1_length=64
nd1_prefix_information1_pltime=120
nd1_prefix_information1_prefix=2a00:23c7:5a1f:d901::
nd1_prefix_information1_vltime=300
nd1_rdnss1_lifetime=60
nd1_rdnss1_servers=fe80::8e83:94ff:fe7f:c989%eno2
nd1_source_address=8c83947fc989
eno2: requesting DHCPv6 information
eno2: Router Advertisement from fe80::cc3:3b37:e1ba:ab76
eno2: dhcp_envoption 24.0/3: malformed embedded option
interface=eno2
pid=101050
protocol=ra
reason=TEST
ifcarrier=up
ifflags=69699
ifmetric=1003
ifmtu=1500
ifwireless=0
nd1_acquired=47696
nd1_addr1=2a00:23c7:5a1f:d901:d99e:cc3f:57b9:7301/64
nd1_flags=O
nd1_from=fe80::8e83:94ff:fe7f:c989
nd1_hoplimit=64
nd1_lifetime=180
nd1_mtu=1492
nd1_now=47696
nd1_prefix_information1_flags=LAH
nd1_prefix_information1_length=64
nd1_prefix_information1_pltime=120
nd1_prefix_information1_prefix=2a00:23c7:5a1f:d901::
nd1_prefix_information1_vltime=300
nd1_rdnss1_lifetime=60
nd1_rdnss1_servers=fe80::8e83:94ff:fe7f:c989%eno2
nd1_source_address=8c83947fc989
nd2_acquired=47696
nd2_addr1=fd4b:566e:90ab:1547:8cbd:8f09:31a6:6384/64
nd2_flags=
nd2_from=fe80::cc3:3b37:e1ba:ab76
nd2_hoplimit=64
nd2_lifetime=0
nd2_now=47696
nd2_prefix_information1_flags=LA
nd2_prefix_information1_length=64
nd2_prefix_information1_pltime=1800
nd2_prefix_information1_prefix=fd4b:566e:90ab:1547::
nd2_prefix_information1_vltime=1800
nd2_route_information1_length=64
nd2_route_information1_lifetime=1800
nd2_source_address=0499b96c36bf
```

The dhcp server is embedded in the router.  I cannot tell if this is a issue with dhcpcd, or an issue with the router which dhcpcd previously ignored or did not detect.  Nor can I tell if there is any impact beyond the overwhelming of the journalctl log.
I'm running KDE Plasma 6.35 on Arch Linux kernel 6.14.10-arch1-1.  

Thanks, Hugh Kernohan

**Comment by rsmarples** [comment]
You need to email it to me directly please, you can't attach and reply to github emails.

**Comment by rsmarples** [comment]
Thanks for the capture, helped to track down the issue.
Can you verify that the branch/patch linked above fixes the issue for you please?

**Comment by TheEpeeist** [comment]
```
12:21 : hugh : ~ >> dhcpcd -U |grep route_info
...
reason=ROUTERADVERT
interface=eno2
protocol=ra
...
nd2_route_information1_length=64
nd2_route_information1_lifetime=1800
```

**Comment by rsmarples** [comment]
So with the patch applied, the output from that command should include `embed truncated ip6address prefix`.
Did you install the patched dhcpcd correctly?

**Comment by TheEpeeist** [comment]
With apologies:  having now patched it correctly the issue has been resolved.

**Comment by toralf** [comment]
I applied that patch here at a hardened Gentoo, but still get it:
```
tfoerste@p14s ~/tmp $ sudo dhcpcd -T 
dhcpcd-10.2.4 starting
dev: loaded udev
DUID 00:01:00:01:2c:78:f6:8b:f4:a8:0d:3d:6a:c4
enp1s0f0: waiting for carrier
wlp2s0: waiting for carrier
enp5s0f4u1u1: IAID 0d:3d:6a:c4
enp5s0f4u1u1: soliciting an IPv6 router
enp5s0f4u1u1: Router Advertisement from fe80::e228:6dff:fe6a:fcc7
enp5s0f4u1u1: dhcp_envoption 24.0/3: missing embedded option
interface=enp5s0f4u1u1
pid=14919
protocol=ra
reason=TEST
skip_hooks=resolv.conf
ifcarrier=up
ifflags=69699
ifmetric=1004
ifmtu=1500
ifwireless=0
nd1_acquired=1431
nd1_addr1=2a02:3100:7fb1:2600:4938:e6de:594e:1a3b/64
nd1_addr2=fd3b:a157:bd8e:0:9b30:a9b2:7c8e:fa08/64
nd1_flags=Oh
nd1_from=fe80::e228:6dff:fe6a:fcc7
nd1_hoplimit=255
nd1_lifetime=1800
nd1_mtu=1492
nd1_now=1431
nd1_prefix_information1_flags=LA
nd1_prefix_information1_length=64
nd1_prefix_information1_pltime=3600
nd1_prefix_information1_prefix=2a02:3100:7fb1:2600::
nd1_prefix_information1_vltime=7200
nd1_prefix_information2_flags=LA
nd1_prefix_information2_length=64
nd1_prefix_information2_pltime=3600
nd1_prefix_information2_prefix=fd3b:a157:bd8e::
nd1_prefix_information2_vltime=7200
nd1_route_information1_length=0
nd1_route_information1_lifetime=1800
nd1_route_information1_prf=08
nd1_route_information2_length=56
nd1_route_information2_lifetime=1800
nd1_route_information2_prefix=2a02:3100:7fb1:2600::
nd1_route_information2_prf=08
nd1_route_information3_length=64
nd1_route_information3_lifetime=1800
nd1_route_information3_prefix=fd3b:a157:bd8e::
nd1_route_information3_prf=08
nd1_source_address=e0286d6afcc7
dhcp6_openudp: Address already in use
dhcp6_start1: Address already in use
enp5s0f4u1u1: rebinding lease of 192.168.178.33
enp5s0f4u1u1: leased 192.168.178.33 for 864000 seconds
enp5s0f4u1u1: dhcp_envoption 24.0/3: missing embedded option
interface=enp5s0f4u1u1
pid=14919
protocol=ra
reason=TEST
skip_hooks=resolv.conf
ifcarrier=up
ifflags=69699
ifmetric=1004
ifmtu=1500
ifwireless=0
nd1_acquired=1431
nd1_addr1=2a02:3100:7fb1:2600:4938:e6de:594e:1a3b/64
nd1_addr2=fd3b:a157:bd8e:0:9b30:a9b2:7c8e:fa08/64
nd1_flags=Oh
nd1_from=fe80::e228:6dff:fe6a:fcc7
nd1_hoplimit=255
nd1_lifetime=1800
nd1_mtu=1492
nd1_now=1431
nd1_prefix_information1_flags=LA
nd1_prefix_information1_length=64
nd1_prefix_information1_pltime=3600
nd1_prefix_information1_prefix=2a02:3100:7fb1:2600::
nd1_prefix_information1_vltime=7200
nd1_prefix_information2_flags=LA
nd1_prefix_information2_length=64
nd1_prefix_information2_pltime=3600
nd1_prefix_information2_prefix=fd3b:a157:bd8e::
nd1_prefix_information2_vltime=7200
nd1_route_information1_length=0
nd1_route_information1_lifetime=1800
nd1_route_information1_prf=08
nd1_route_information2_length=56
nd1_route_information2_lifetime=1800
nd1_route_information2_prefix=2a02:3100:7fb1:2600::
nd1_route_information2_prf=08
nd1_route_information3_length=64
nd1_route_information3_lifetime=1800
nd1_route_information3_prefix=fd3b:a157:bd8e::
nd1_route_information3_prf=08
nd1_source_address=e0286d6afcc7
dhcpcd exited
```

**Comment by rsmarples** [comment]
@toralf That looks like a different error. Could you open a new ticket please and attach a tcpdump of the DHCP transaction or the lease file saved please?
